
from html import escape
import pandas as pd


def build_html_report(df, profile):
    missing = int(df.isna().sum().sum())
    duplicates = int(df.duplicated().sum())
    memory_mb = df.memory_usage(deep=True).sum() / 1024**2

    profile_html = profile.to_html(index=False, classes="profile", border=0)

    preview = df.head(20).to_html(index=False, classes="preview", border=0)

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>CSV Data Analysis Report</title>
<style>
body{{font-family:Arial,sans-serif;background:#f8fafc;color:#172033;margin:0;padding:32px}}
.container{{max-width:1200px;margin:auto}}
h1{{margin-bottom:4px}} h2{{margin-top:34px}}
.cards{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}}
.card{{background:white;padding:18px;border-radius:12px;border:1px solid #e2e8f0}}
.value{{font-size:28px;font-weight:bold;margin-top:5px}}
.table-wrap{{overflow:auto;background:white;border-radius:12px;border:1px solid #e2e8f0}}
table{{border-collapse:collapse;width:100%;font-size:13px}}
th,td{{padding:8px 10px;border-bottom:1px solid #e2e8f0;text-align:left}}
th{{background:#f1f5f9}}
</style>
</head>
<body>
<div class="container">
<h1>CSV Data Analysis Report</h1>
<p>Generated by CSV Data Analyzer.</p>

<div class="cards">
<div class="card">Rows<div class="value">{len(df):,}</div></div>
<div class="card">Columns<div class="value">{len(df.columns):,}</div></div>
<div class="card">Missing Cells<div class="value">{missing:,}</div></div>
<div class="card">Duplicate Rows<div class="value">{duplicates:,}</div></div>
</div>

<h2>Dataset Details</h2>
<ul>
<li>Memory usage: {memory_mb:.2f} MB</li>
<li>Numeric columns: {len(df.select_dtypes(include="number").columns)}</li>
<li>Text/category columns: {len(df.select_dtypes(exclude="number").columns)}</li>
</ul>

<h2>Column Profile</h2>
<div class="table-wrap">{profile_html}</div>

<h2>First 20 Rows</h2>
<div class="table-wrap">{preview}</div>
</div>
</body>
</html>"""
